import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Next.js app - Blog",
  description: "Generated by create next app",
};


export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <p>Blog Layout</p>
      {children}
    </div>
  );
}
